import { mkdir, readdir, readFile, lstat, stat, symlink, readlink, unlink, rmdir, rename, writeFile, open } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { join, basename, dirname } from 'node:path';
import type { LocalProfile, VaultGraph, VaultInfo, VaultTarget } from '../shared/types';
import { validateId, validateProfile, string as str } from '../shared/domain';
import { buildGraph, buildMessages, cwdFromTranscript, homeNote, hubNote, isGenerated, matchTargets, parseAnswer, parseFrontmatter, pickNotes, TYPES, uniqueNames, wikilinks, type NoteMeta } from '../shared/vault';
import type { ProviderClient } from './providers';

interface Project { slug: string; name: string; cwd: string; memoryDir: string; }
const head = async (file: string, bytes: number): Promise<string> => { const h = await open(file, 'r'); try { const b = Buffer.alloc(bytes); const { bytesRead } = await h.read(b, 0, bytes, 0); return b.toString('utf8', 0, bytesRead); } finally { await h.close(); } };
const norm = (p: string) => p.replace(/^\\\\\?\\/, '').replace(/[\\/]+$/, '').toLowerCase();
export const samePath = (a: string, b: string): boolean => norm(a) === norm(b);
/** Junction removal: unlink works on most Node builds, rmdir on the rest. Never reaches a real directory because callers check lstat first. */
const removeLink = async (p: string) => { try { await unlink(p); } catch { await rmdir(p); } };
const typeOf = (n: NoteMeta) => (TYPES as readonly string[]).includes(n.type) ? n.type : 'other';
const GRAPH_JSON = JSON.stringify({ colorGroups: [{ query: 'path:Projects', color: { a: 1, rgb: 5814783 } }, { query: 'path:Types', color: { a: 1, rgb: 15763518 } }, { query: 'file:Home', color: { a: 1, rgb: 15132390 } }], showTags: false, showAttachments: false, showOrphans: true, centerStrength: 0.5, repelStrength: 12, linkStrength: 1, linkDistance: 120 }, null, 2);

export class MemoryVault {
  protected notes: NoteMeta[] = []; protected projects: Project[] = []; protected last: VaultInfo | null = null; private running: Promise<VaultInfo> | null = null;
  constructor(public path: string, private claudeDir: string, private obsidianExe: string, protected obsidianRegistry: string, protected providers: ProviderClient) {}
  obsidianInstalled(): boolean { return existsSync(this.obsidianExe); }
  info(): Promise<VaultInfo> { return this.last ? Promise.resolve(this.last) : this.scan(); }
  scan(): Promise<VaultInfo> { if (!this.running) this.running = this.doScan().finally(() => { this.running = null; }); return this.running; }
  private async doScan(): Promise<VaultInfo> {
    const info: VaultInfo = { path: this.path, projects: 0, notes: 0, obsidian: this.obsidianInstalled(), scannedAt: new Date().toISOString(), message: '' };
    try {
      const projectsDir = join(this.claudeDir, 'projects'), skipped: string[] = [];
      for (const d of ['Projects', 'Types', '.obsidian']) await mkdir(join(this.path, d), { recursive: true });
      const projects = await this.discover(projectsDir), notes = await this.readNotes(projects);
      this.projects = projects; this.notes = notes; info.projects = projects.length; info.notes = notes.length;
      // Every junction and hub is its own attempt: one bad entry under Projects\ must not stop the rest or stale the counts.
      const attempt = async (label: string, fn: () => Promise<void>) => { try { await fn(); } catch (error) { skipped.push(`${label}: ${(error as Error).message}`); } };
      await attempt('junctions', () => this.syncJunctions(projects, skipped));
      const write = (file: string, text: string) => attempt(basename(file), async () => { try { if (!isGenerated(await readFile(file, 'utf8'))) { skipped.push(`${basename(file)} is not generated by AlphaCode, left alone`); return; } } catch { /* absent: write it */ } await writeFile(file, text, 'utf8'); });
      const keep = new Set<string>();
      for (const p of projects) { keep.add(`${p.name}.md`); const index = existsSync(join(p.memoryDir, 'MEMORY.md')) ? ` · [[Projects/${p.name}/MEMORY|Claude's own index]]` : ''; await write(join(this.path, 'Projects', `${p.name}.md`), hubNote(p.name, notes.filter(n => n.project === p.name), `Working directory: \`${p.cwd || 'unknown'}\`${index}`)); }
      const types = [...TYPES, ...(notes.some(n => typeOf(n) === 'other') ? ['other'] : [])];
      for (const t of types) await write(join(this.path, 'Types', `${t}.md`), hubNote(t, notes.filter(n => typeOf(n) === t)));
      await write(join(this.path, 'Home.md'), homeNote(projects.map(p => ({ name: p.name, count: notes.filter(n => n.project === p.name).length })), types.map(t => ({ type: t, count: notes.filter(n => typeOf(n) === t).length })), projectsDir, info.scannedAt));
      for (const f of await readdir(join(this.path, 'Projects'))) if (f.endsWith('.md') && !keep.has(f)) await attempt(f, async () => { const file = join(this.path, 'Projects', f); if ((await lstat(file)).isFile() && isGenerated(await readFile(file, 'utf8'))) await unlink(file); });
      for (const [f, text] of [['app.json', '{}'], ['graph.json', GRAPH_JSON]] as const) { const file = join(this.path, '.obsidian', f); if (!existsSync(file)) await writeFile(file, text, 'utf8'); }
      if (skipped.length) info.message = skipped.join('; ');
    } catch (error) { info.message = (error as Error).message; }
    this.last = info; return info;
  }
  /** Adds this vault to Obsidian's vault list when missing, written without a byte-order mark (Obsidian cannot parse one). True when an entry was added. */
  async register(): Promise<boolean> {
    let reg: any = {}; try { reg = JSON.parse(await readFile(this.obsidianRegistry, 'utf8')); } catch { /* no registry yet */ }
    if (!reg || typeof reg !== 'object') reg = {}; if (!reg.vaults || typeof reg.vaults !== 'object') reg.vaults = {};
    if (Object.values(reg.vaults).some((v: any) => typeof v?.path === 'string' && samePath(v.path, this.path))) return false;
    reg.vaults[randomBytes(8).toString('hex')] = { path: this.path, ts: Date.now() };
    await mkdir(dirname(this.obsidianRegistry), { recursive: true });
    const temporary = `${this.obsidianRegistry}.alphacode-tmp`; await writeFile(temporary, JSON.stringify(reg), { encoding: 'utf8' }); await rename(temporary, this.obsidianRegistry);
    return true;
  }
  private async discover(projectsDir: string): Promise<Project[]> {
    let slugs: string[] = []; try { slugs = (await readdir(projectsDir, { withFileTypes: true })).filter(d => d.isDirectory()).map(d => d.name); } catch { return []; }
    const found: { slug: string; cwd: string; memoryDir: string }[] = [];
    for (const slug of slugs) {
      const dir = join(projectsDir, slug), memoryDir = join(dir, 'memory'); try { if (!(await stat(memoryDir)).isDirectory()) continue; } catch { continue; }
      let cwd = '';
      try { const logs = await Promise.all((await readdir(dir)).filter(f => f.endsWith('.jsonl')).map(async f => ({ f, m: (await stat(join(dir, f))).mtimeMs }))); logs.sort((a, b) => b.m - a.m); for (const { f } of logs) { cwd = cwdFromTranscript(await head(join(dir, f), 65536)); if (cwd) break; } } catch { /* no transcript: slug is the name */ }
      found.push({ slug, cwd, memoryDir });
    }
    const names = uniqueNames(found); return found.map(f => ({ ...f, name: names.get(f.slug)! }));
  }
  private async readNotes(projects: Project[]): Promise<NoteMeta[]> {
    const notes: NoteMeta[] = [];
    for (const p of projects) {
      let files: string[] = []; try { files = (await readdir(p.memoryDir)).filter(f => f.endsWith('.md') && f !== 'MEMORY.md'); } catch { continue; }
      // ponytail: whole note bodies (16 KB cap) stay in memory; index to disk if vaults reach tens of thousands of notes.
      for (const f of files) try { const text = await head(join(p.memoryDir, f), 16384), fm = parseFrontmatter(text); notes.push({ name: f.slice(0, -3), description: fm.description || '', type: fm.type || 'other', modified: fm.modified || '', project: p.name, file: join(p.memoryDir, f), links: wikilinks(text), body: text }); } catch { /* unreadable note is skipped this scan */ }
    }
    return notes;
  }
  private async syncJunctions(projects: Project[], skipped: string[]): Promise<void> {
    const dir = join(this.path, 'Projects'), wanted = new Map(projects.map(p => [p.name, p.memoryDir]));
    for (const name of await readdir(dir)) {
      const link = join(dir, name); if (!(await lstat(link)).isSymbolicLink()) continue;
      let target = ''; try { target = await readlink(link); } catch { /* broken link */ }
      const want = wanted.get(name); if (want && samePath(target, want) && existsSync(want)) { wanted.delete(name); continue; }
      try { await removeLink(link); } catch (error) { skipped.push(`${name}: ${(error as Error).message}`); wanted.delete(name); }
    }
    for (const [name, target] of wanted) try { await symlink(target, join(dir, name), 'junction'); } catch (error) { skipped.push(`${name}: ${(error as NodeJS.ErrnoException).code === 'EEXIST' ? 'a real folder or file with this name is in the way' : (error as Error).message}`); }
  }
  graph(): VaultGraph { return buildGraph(this.notes); }
  async ask(paneId: string, profile: LocalProfile, question: string): Promise<{ answer: string; notes: string[] }> {
    validateId(paneId); const p = validateProfile(profile), q = str(question, 'question', 4000); if (!q.trim()) throw new Error('Ask something first.');
    if (!this.last) await this.scan();
    const context = pickNotes(this.notes, q);
    const text = await this.providers.chat(paneId, { ...p, systemPrompt: '' }, buildMessages(context, q));
    return parseAnswer(text, context.map(n => n.name));
  }
  private async obsidianVaults(): Promise<{ name: string; path: string }[]> {
    try { const reg = JSON.parse(await readFile(this.obsidianRegistry, 'utf8')); return Object.values(reg.vaults || {}).flatMap((v: any) => typeof v?.path === 'string' && v.path ? [{ name: basename(v.path), path: v.path }] : []); } catch { return []; }
  }
  async resolve(name: string, workspaces: { id: string; name: string }[]): Promise<VaultTarget[]> {
    const query = str(name, 'target name', 200); if (!Array.isArray(workspaces) || workspaces.length > 50) throw new Error('Invalid workspace list');
    if (!this.last) await this.scan();
    return matchTargets(query, [
      ...this.projects.filter(p => p.cwd).map(p => ({ kind: 'project' as const, name: p.name, path: p.cwd })),
      ...(await this.obsidianVaults()).map(v => ({ kind: 'obsidian' as const, ...v })),
      ...workspaces.map(w => ({ kind: 'workspace' as const, name: str(w.name, 'workspace name', 100), path: validateId(w.id) })),
    ]);
  }
  async obsidianUrl(path: string): Promise<string> {
    const p = str(path, 'vault path', 32768); if (!(await this.obsidianVaults()).some(v => samePath(v.path, p))) throw new Error('That folder is not a registered Obsidian vault.');
    return `obsidian://open?path=${encodeURIComponent(p)}`;
  }
}
