import { mkdir, readdir, readFile, lstat, stat, symlink, readlink, unlink, rmdir, writeFile, open } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, basename } from 'node:path';
import type { VaultInfo } from '../shared/types';
import { cwdFromTranscript, homeNote, hubNote, isGenerated, parseFrontmatter, TYPES, uniqueNames, wikilinks, type NoteMeta } from '../shared/vault';
import type { ProviderClient } from './providers';

interface Project { slug: string; name: string; cwd: string; memoryDir: string; }
const head = async (file: string, bytes: number): Promise<string> => { const h = await open(file, 'r'); try { const b = Buffer.alloc(bytes); const { bytesRead } = await h.read(b, 0, bytes, 0); return b.toString('utf8', 0, bytesRead); } finally { await h.close(); } };
const norm = (p: string) => p.replace(/^\\\\\?\\/, '').replace(/[\\/]+$/, '').toLowerCase();
export const samePath = (a: string, b: string): boolean => norm(a) === norm(b);
/** Junction removal: unlink works on most Node builds, rmdir on the rest. Never reaches a real directory because callers check lstat first. */
const removeLink = async (p: string) => { try { await unlink(p); } catch { await rmdir(p); } };
const typeOf = (n: NoteMeta) => (TYPES as readonly string[]).includes(n.type) ? n.type : 'other';
const GRAPH_JSON = JSON.stringify({ colorGroups: [{ query: 'path:Projects', color: { a: 1, rgb: 5814783 } }, { query: 'path:Types', color: { a: 1, rgb: 15763518 } }, { query: 'file:Home', color: { a: 1, rgb: 15132390 } }], showTags: false, showAttachments: false, showOrphans: true, centerStrength: 0.5, repelStrength: 12, linkStrength: 1, linkDistance: 120 }, null, 2);

export class MemoryVault {
  protected notes: NoteMeta[] = []; protected projects: Project[] = []; protected last: VaultInfo | null = null; private running: Promise<VaultInfo> | null = null;
  constructor(public path: string, private claudeDir: string, private obsidianExe: string, protected obsidianRegistry: string, protected providers: ProviderClient) {}
  obsidianInstalled(): boolean { return existsSync(this.obsidianExe); }
  info(): Promise<VaultInfo> { return this.last ? Promise.resolve(this.last) : this.scan(); }
  scan(): Promise<VaultInfo> { if (!this.running) this.running = this.doScan().finally(() => { this.running = null; }); return this.running; }
  private async doScan(): Promise<VaultInfo> {
    const info: VaultInfo = { path: this.path, projects: 0, notes: 0, obsidian: this.obsidianInstalled(), scannedAt: new Date().toISOString(), message: '' };
    try {
      const projectsDir = join(this.claudeDir, 'projects'), skipped: string[] = [];
      for (const d of ['Projects', 'Types', '.obsidian']) await mkdir(join(this.path, d), { recursive: true });
      const projects = await this.discover(projectsDir), notes = await this.readNotes(projects);
      await this.syncJunctions(projects);
      const write = async (file: string, text: string) => { try { if (!isGenerated(await readFile(file, 'utf8'))) { skipped.push(basename(file)); return; } } catch { /* absent: write it */ } await writeFile(file, text, 'utf8'); };
      const keep = new Set<string>();
      for (const p of projects) { keep.add(`${p.name}.md`); await write(join(this.path, 'Projects', `${p.name}.md`), hubNote(p.name, notes.filter(n => n.project === p.name), `Working directory: \`${p.cwd || 'unknown'}\` · [[Projects/${p.name}/MEMORY|Claude's own index]]`)); }
      const types = [...TYPES, ...(notes.some(n => typeOf(n) === 'other') ? ['other'] : [])];
      for (const t of types) await write(join(this.path, 'Types', `${t}.md`), hubNote(t, notes.filter(n => typeOf(n) === t)));
      await write(join(this.path, 'Home.md'), homeNote(projects.map(p => ({ name: p.name, count: notes.filter(n => n.project === p.name).length })), types.map(t => ({ type: t, count: notes.filter(n => typeOf(n) === t).length })), projectsDir, info.scannedAt));
      for (const f of await readdir(join(this.path, 'Projects'))) if (f.endsWith('.md') && !keep.has(f)) { const file = join(this.path, 'Projects', f); if (isGenerated(await readFile(file, 'utf8'))) await unlink(file); }
      for (const [f, text] of [['app.json', '{}'], ['graph.json', GRAPH_JSON]] as const) { const file = join(this.path, '.obsidian', f); if (!existsSync(file)) await writeFile(file, text, 'utf8'); }
      this.projects = projects; this.notes = notes; info.projects = projects.length; info.notes = notes.length;
      if (skipped.length) info.message = `Not overwritten (not generated by AlphaCode): ${skipped.join(', ')}`;
    } catch (error) { info.message = (error as Error).message; }
    this.last = info; return info;
  }
  private async discover(projectsDir: string): Promise<Project[]> {
    let slugs: string[] = []; try { slugs = (await readdir(projectsDir, { withFileTypes: true })).filter(d => d.isDirectory()).map(d => d.name); } catch { return []; }
    const found: { slug: string; cwd: string; memoryDir: string }[] = [];
    for (const slug of slugs) {
      const dir = join(projectsDir, slug), memoryDir = join(dir, 'memory'); try { if (!(await stat(memoryDir)).isDirectory()) continue; } catch { continue; }
      let cwd = '';
      try { const logs = await Promise.all((await readdir(dir)).filter(f => f.endsWith('.jsonl')).map(async f => ({ f, m: (await stat(join(dir, f))).mtimeMs }))); logs.sort((a, b) => b.m - a.m); for (const { f } of logs) { cwd = cwdFromTranscript(await head(join(dir, f), 65536)); if (cwd) break; } } catch { /* no transcript: slug is the name */ }
      found.push({ slug, cwd, memoryDir });
    }
    const names = uniqueNames(found); return found.map(f => ({ ...f, name: names.get(f.slug)! }));
  }
  private async readNotes(projects: Project[]): Promise<NoteMeta[]> {
    const notes: NoteMeta[] = [];
    for (const p of projects) {
      let files: string[] = []; try { files = (await readdir(p.memoryDir)).filter(f => f.endsWith('.md') && f !== 'MEMORY.md'); } catch { continue; }
      // ponytail: whole note bodies (16 KB cap) stay in memory; index to disk if vaults reach tens of thousands of notes.
      for (const f of files) try { const text = await head(join(p.memoryDir, f), 16384), fm = parseFrontmatter(text); notes.push({ name: f.slice(0, -3), description: fm.description || '', type: fm.type || 'other', modified: fm.modified || '', project: p.name, file: join(p.memoryDir, f), links: wikilinks(text), body: text }); } catch { /* unreadable note is skipped this scan */ }
    }
    return notes;
  }
  private async syncJunctions(projects: Project[]): Promise<void> {
    const dir = join(this.path, 'Projects'), wanted = new Map(projects.map(p => [p.name, p.memoryDir]));
    for (const name of await readdir(dir)) {
      const link = join(dir, name); if (!(await lstat(link)).isSymbolicLink()) continue;
      let target = ''; try { target = await readlink(link); } catch { /* broken link */ }
      const want = wanted.get(name); if (want && samePath(target, want) && existsSync(want)) { wanted.delete(name); continue; }
      await removeLink(link);
    }
    for (const [name, target] of wanted) await symlink(target, join(dir, name), 'junction');
  }
}
